[package]
name = "kad4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencode = { path = "/home/brad/CLionProjects/BencodeRust" }

[lib]
name = "kad4"
path = "src/lib.rs"
